### PR TITLE
Learnable arcane spells

### PR DESCRIPTION
**Pull request by 4Luke4**
I added a variable for each scroll that allows you to learn an arcane spell – I purposely skipped "Summon Cow" (`SCRLZZ // and related aliases like ~SCRLZY~`) and the scrolls you can find during the tutorial (e.g.: `TTSCRL02`).

### CODE REVIEW

**Comment by burner1024** [comment]
Hmm.
1. scroll.ids actually [exists](https://iesdp.bgforge.net/files/ids/bg2/scroll.htm) in ToB and apparenly it's used for other purposes. I think it's better to rename the file to avoid misleading. I mean, it's not an actual IDS, right?
2. Maybe it's more intuitive to move SCROLL to prefix? `SCROLL_WIZARD_FAR_SIGHT`. That's what I'd probably expect to see in the code and when typing.

**Comment by 4Luke4** [comment]
> 1. `scroll.ids` actually [exists](https://iesdp.bgforge.net/files/ids/bg2/scroll.htm) in ToB and apparenly it's used for other purposes. I think it's better to rename the file to avoid misleading. I mean, it's not an actual IDS, right?

No, it's not an actual IDS, but it's built from IDS entries, hence the name and location.
What about "learnable_spell.ids"?

> 2. Maybe it's more intuitive to move SCROLL to prefix? `SCROLL_WIZARD_FAR_SIGHT`. That's what I'd probably expect to see in the code and when typing.

OK, I'll do it (I took inspiration from SCS, as always).

**Comment by burner1024** [comment]
> it's built from IDS entries, hence the name.

Sorry, which entries do you mean? I don't think scrolls are listed anywhere?
My point is, we'll probably have actual scroll.ids added sometime, and then filename will conflict.

> What about "learnable_spell.ids"?

What's that, what about it?

**Comment by 4Luke4** [comment]
> > it's built from IDS entries, hence the name.
> 
> Sorry, which entries do you mean? I don't think scrolls are listed anywhere?
> My point is, we'll probably have actual scroll.ids added sometime, and then filename will conflict.

Variables names are built from `SPELL.IDS`. Here is how I generated them:
```
DEFINE_ACTION_MACRO "SCROLL_IDS" BEGIN
	LOCAL_SET "SOURCE_SIZE" = 0
	LOCAL_SET "category" = 0
	LOCAL_SPRINT "ab_array" ""
	LOCAL_SPRINT "ind" ""
	LOCAL_SPRINT "ab_offset" ""
	LOCAL_SPRINT "fx_array" ""
	LOCAL_SPRINT "ind2" ""
	LOCAL_SPRINT "fx_offset" ""
	LOCAL_SET "opcode" = 0
	LOCAL_SPRINT "resource" ""
	LOCAL_SPRINT "spell_name" ""

	COPY_EXISTING_REGEXP - ~^.+\.itm$~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			READ_SHORT 0x1C "category"
			PATCH_IF ("%category%" == 11) BEGIN	// Scrolls
				GET_OFFSET_ARRAY ~ab_array~ ITM_V10_HEADERS
				PHP_EACH ~ab_array~ AS ~ind~ => ~ab_offset~ BEGIN
					GET_OFFSET_ARRAY2 ~fx_array~ ~%ab_offset%~ ITM_V10_HEAD_EFFECTS
					PHP_EACH ~fx_array~ AS ~ind2~ => ~fx_offset~ BEGIN
						READ_SHORT ("%fx_offset%" + 0x0) "opcode"
						PATCH_IF ("%opcode%" == 147) BEGIN	// Learn spell
							READ_ASCII ("%fx_offset%" + 0x14) "resource" (8) NULL
							PATCH_IF (("%resource%" STRING_CONTAINS_REGEXP "SPWI") == 0) BEGIN
								LPF "NAME_NUM_OF_SPELL_RES"
								STR_VAR
									"spell_res" = "%resource%"
								RET
									"spell_name"
								END
								PATCH_LOG "TEXT_SPRINT ~SCROLL_%spell_name%~ ~%SOURCE_RES%~"
							END
							CLEAR_ARRAY "fx_array"
							CLEAR_ARRAY "ab_array"
						END
					END
				END
			END
		END
	BUT_ONLY_IF_IT_CHANGES
END
```

> 
> > What about "learnable_spell.ids"?
> 
> What's that, what about it?

I meant what filename do you suggest?

**Comment by burner1024** [comment]
I don't know, just `scrolls.tpp` will do I guess. I would keep `ids` for actual IDS files, just for sanity.

**Comment by 4Luke4** [comment]
> I don't know, just `scrolls.tpp` will do I guess. I would keep `ids` for actual IDS files, just for sanity.

OK. Should I change file location too?

**Comment by burner1024** [comment]
Probably better to do that, yes. As you can see, I started organizing the files, as there was too much in the root, but it's only halfway done.
If you plan to add more items later, could dedicate a separate dir for them. Otherwise, could name it something like "misc" or "extra". Icons would then go there too.

It's not really critical, we can always re-arrange at any point.

**Comment by 4Luke4** [comment]
> Otherwise, could name it something like "misc" or "extra".

Put them in `misc`.

**Comment by burner1024** [comment]
Cool, thanks!

**Comment by burner1024** [comment]
@4Luke4 why did you skip other scrolls?

**Comment by 4Luke4** [comment]
> @4Luke4 why did you skip other scrolls?

Do you mean divine ones?

**Comment by burner1024** [comment]
Unlearnable wizard's.
I'm just thinking of adding some more stuff (protection scrolls), so I'd like to be clear about why just learnable wizards were chosen.

**Comment by 4Luke4** [comment]
> Unlearnable wizard's.
> I'm just thinking of adding some more stuff (protection scrolls), so I'd like to be clear about why just learnable wizards were chosen.

Yeah, adding protection scrolls sounds good, go for it.
As for why just learnable wizards were chosen: no particular reason. Probably because in case you need to adjust the description of a particular wizard spell, you also need the scroll referencing the corresponding spell (so as to adjust both descriptions...)

**Comment by burner1024** [comment]
ok, I see

**Pull request merged**
