### PR TITLE
SPELL.IDS

### PR DESCRIPTION
**Pull request by 4Luke4**
Added `SPELL.IDS` constants.

### CODE REVIEW

**Comment by burner1024** [comment]
This basically the same as SFO does, right? But why do you lowecase the names?
Also, if I understand correctly, the code will print the list of all spells each time it's included?

**Comment by 4Luke4** [comment]
Yes, I expect it to be somewhat similar to SFO...

> But why do you lowecase the names?

Well, I usually write `variables` in lowercase letters... Feel free to comment it out / remove that line if you wish...

> Also, if I understand correctly, the code will print the list of all spells each time it's included?

Yes, correct (useful for debugging). Feel free to comment it out / remove that line if you wish...

**Comment by burner1024** [comment]
I made both changes. Reasoning, for the reference:
1. I also usually use lowercase variables, but these defines are really constants, not vars. Other includes in IElib, SFO and WeiDU itself use uppercase names for constants. It's kind of a visual cue, and all things being equal, I'd prefer to be consistent.
2. Included with `ALWAYS`, it'll pollute the log with the same list for every component. I don't think that's helpful. If there's a need, we could always add a debug flag or something.

**Comment by burner1024** [comment]
And thank you for this addition.

**Comment by 4Luke4** [comment]
> 1. I also usually use lowercase variables, but these defines are really constants, not vars. Other includes in IElib, SFO and WeiDU itself use uppercase names for constants. It's kind of a visual cue, and all things being equal, I'd prefer to be consistent.

OK, fine.

> 2. Included with ALWAYS, it'll pollute the log with the same list for every component. I don't think that's helpful. If there's a need, we could always add a debug flag or something.

Yeah, that `PATCH_PRINT` was really meant to see if the code did what I expected from it...

However, all those variables (constants) should be included just once... instead of once per component (if used by more than one component). More info [here](https://github.com/Gibberlings3/immutable/blob/master/mymod/lib/always.tph)...

**Pull request merged**
